---

- hosts: localhost
  connection: local
  become: true
  vars:
    whoami: "{{ lookup('env', 'USER') }}"
    user_home: "{{ lookup('env', 'HOME') }}"
    git_user_name: "Craig Dallimore"
    git_user_email: "decoy9697@gmail.com"
    role_basic_done: false
  roles:
    - basic
