---

nvm:
  path: '~/.nvm'
  version: v0.32.1
  node_version: '6.9.4'

dockitems_to_remove:
  - Launchpad
  - Mail
  - Safari
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iTunes
  - iBooks
  - App Store
  - System Preferences
  - Calendar

dockitems_to_persist:
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
    pos: 1
  - name: Slack
    path: "/Applications/Slack.app"
    pos: 4



